apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-hello
spec:
  selector:
    matchLabels:
      app: worker-hello
      tier: backend
      track: stable
  replicas:  15
  template:
    metadata:
      labels:
        app: worker-hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: worker-hello
          image: golang:1.10-alpine
          command:
            - sleep
            - "3600"
